CREATE TABLE MUSEUM(
Id_Museum INT PRIMARY KEY,
MuseumName NVARCHAR(50) NOT NULL,
City NVARCHAR(50) NOT NULL,
)

CREATE TABLE ARTIST(
Id_Artist INT PRIMARY KEY,
Name NVARCHAR(50),
Country NVARCHAR(50) NOT NULL,
)

CREATE TABLE CHARCATER(
ID_Character INT PRIMARY KEY,
Name NVARCHAR(50),
)

CREATE TABLE ARTWORK(
ID_Artwork INT PRIMARY KEY,
Name NVARCHAR(50) NOT NULL,
ID_Museum INT NOT NULL REFERENCES MUSEUM,
ID_Artist INT NOT NULL REFERENCES ARTIST,
ID_Character INT NULL REFERENCES CHARCATER,
)